using System.Net;
using System.Net.Http.Json;
using System.Text.RegularExpressions;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Horse_BackEnd.Data;
using Horse_BackEnd.Domain;
using Horse_BackEnd.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Horse_BackEnd.Tests;

public sealed class StorageSqlServerTests
{
    [SqlServerFact]
    public async Task NativeSqlBackupRestoresIntoNewTestDatabaseAndApiCanReadUploadedFile()
    {
        await using var source = new ClubFactory(); var owner = await source.User(Role.HorseOwner); using var client = await source.Client(owner);
        var registration = await StorageRecoveryTests.Registration(source, owner);
        using var form = StorageRecoveryTests.Upload(); var upload = await client.PostAsync($"/api/registrations/{registration.Id}/attachments", form);
        var attachmentId = (await upload.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>()).GetProperty("id").GetGuid();
        var sourceConfig = source.Services.GetRequiredService<IConfiguration>();
        await using var target = new ClubFactory(new Dictionary<string, string?>
        { ["Storage:Path"] = sourceConfig["Storage:Path"], ["DataProtection:Path"] = sourceConfig["DataProtection:Path"] });
        var sourceName = new SqlConnectionStringBuilder(source.SqlTestConnection).InitialCatalog;
        var targetName = new SqlConnectionStringBuilder(target.SqlTestConnection).InitialCatalog;
        Assert.Matches("^HRCMS_Test_[a-f0-9]{32}$", sourceName); Assert.Matches("^HRCMS_Test_[a-f0-9]{32}$", targetName);
        await using var master = new SqlConnection(new SqlConnectionStringBuilder(source.SqlTestConnection) { InitialCatalog = "master" }.ConnectionString);
        await master.OpenAsync();
        async Task<string> Property(string name)
        {
            await using var command = new SqlCommand("SELECT CONVERT(nvarchar(4000), SERVERPROPERTY(@property))", master); command.Parameters.AddWithValue("@property", name);
            return (string?)await command.ExecuteScalarAsync() ?? throw new InvalidOperationException("SQL Server default directories required for backup drill.");
        }
        string Join(string directory, string file) => directory.TrimEnd('/', '\\') + (directory.Contains('\\') ? "\\" : "/") + file;
        var backupName = "HRCMS_Recovery_" + Guid.NewGuid().ToString("N") + ".bak";
        var backup = Join(await Property("InstanceDefaultBackupPath"), backupName);
        var data = Join(await Property("InstanceDefaultDataPath"), targetName + ".mdf");
        var log = Join(await Property("InstanceDefaultLogPath"), targetName + ".ldf");
        var logical = new Dictionary<int, string>();
        await using (var command = new SqlCommand("SELECT type, name FROM sys.master_files WHERE database_id=DB_ID(@database)", master))
        {
            command.Parameters.AddWithValue("@database", sourceName); await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync()) logical.Add(reader.GetByte(0), reader.GetString(1));
        }
        async Task Execute(string sql)
        {
            await using var command = new SqlCommand(sql, master) { CommandTimeout = 60 };
            command.Parameters.AddWithValue("@source", sourceName); command.Parameters.AddWithValue("@target", targetName);
            command.Parameters.AddWithValue("@backup", backup); command.Parameters.AddWithValue("@data", data); command.Parameters.AddWithValue("@log", log);
            command.Parameters.AddWithValue("@logicalData", logical[0]); command.Parameters.AddWithValue("@logicalLog", logical[1]);
            await command.ExecuteNonQueryAsync();
        }
        try
        {
            await Execute("BACKUP DATABASE @source TO DISK=@backup WITH COPY_ONLY, CHECKSUM;");
            await Execute("RESTORE VERIFYONLY FROM DISK=@backup WITH CHECKSUM;");
            await Execute("RESTORE DATABASE @target FROM DISK=@backup WITH MOVE @logicalData TO @data, MOVE @logicalLog TO @log, CHECKSUM;");
            using var restoredClient = await target.Client(owner);
            Assert.Equal(StorageRecoveryTests.Png, await restoredClient.GetByteArrayAsync($"/api/registrations/{registration.Id}/attachments/{attachmentId}"));
            await WorkerTests.Read(target, async db =>
            {
                Assert.Equal(owner.Id, (await db.Registrations.FindAsync(registration.Id))!.OwnerId);
                Assert.Equal(db.Database.GetMigrations(), await db.Database.GetAppliedMigrationsAsync());
            });
        }
        finally
        {
            // Names and paths are generated by this fixture, never supplied as a restore target by a user.
            await target.DisposeAsync();
            await using var cleanup = new Horse_BackEnd.Data.SqlServerClubDbContext(new DbContextOptionsBuilder<Horse_BackEnd.Data.SqlServerClubDbContext>().UseSqlServer(target.SqlTestConnection).Options);
            await cleanup.Database.EnsureDeletedAsync();
            if (!Regex.IsMatch(backupName, "^HRCMS_Recovery_[a-f0-9]{32}\\.bak$")) throw new InvalidOperationException("Unsafe backup cleanup.");
            await Execute("EXEC master.dbo.xp_delete_file 0, @backup;");
        }
    }
    [SqlServerFact]
    public async Task FailedIncidentPhotoInsertRollsBackRowsAuditAndFilesystem()
    {
        await using var factory = new ClubFactory(); var owner = await factory.User(Role.HorseOwner); using var client = await factory.Client(owner);
        var horse = await factory.Horse(owner);
        var incident = new Incident { HorseId = horse.Id, ReporterId = owner.Id, RoutedTo = Role.Veterinarian };
        await WorkerTests.Read(factory, async db =>
        {
            db.Incidents.Add(incident); await db.SaveChangesAsync();
            await db.Database.ExecuteSqlRawAsync("CREATE TRIGGER RejectIncidentPhoto ON IncidentPhotos AFTER INSERT AS THROW 51000, 'Injected photo failure', 1;");
        });
        using var form = StorageRecoveryTests.Upload();
        Assert.Equal(HttpStatusCode.Conflict, (await client.PostAsync($"/api/care/incidents/{incident.Id}/photos", form)).StatusCode);
        await WorkerTests.Read(factory, async db => { Assert.Empty(await db.IncidentPhotos.ToListAsync()); Assert.Empty(await db.Audit.ToListAsync()); });
        using var scope = factory.Services.CreateScope(); Assert.Empty(Directory.GetFiles(scope.ServiceProvider.GetRequiredService<UploadStorage>().Root));
    }
    [SqlServerFact]
    public async Task FailedAttachmentInsertRollsBackRowsAuditAndFilesystem()
    {
        await using var factory = new ClubFactory(); var owner = await factory.User(Role.HorseOwner); using var client = await factory.Client(owner);
        var registration = await StorageRecoveryTests.Registration(factory, owner);
        await WorkerTests.Read(factory, async db => await db.Database.ExecuteSqlRawAsync("CREATE TRIGGER RejectAttachment ON Attachments AFTER INSERT AS THROW 51000, 'Injected attachment failure', 1;"));
        using var form = StorageRecoveryTests.Upload(); var response = await client.PostAsync($"/api/registrations/{registration.Id}/attachments", form);
        Assert.Equal(HttpStatusCode.Conflict, response.StatusCode);
        await WorkerTests.Read(factory, async db => { Assert.Empty(await db.Attachments.ToListAsync()); Assert.Empty(await db.Audit.ToListAsync()); });
        using var scope = factory.Services.CreateScope(); Assert.Empty(Directory.GetFiles(scope.ServiceProvider.GetRequiredService<UploadStorage>().Root));
    }
}
