using System.Text.Json;
using HorseClub.DAL.Entities;
using HorseClub.DAL.Enums;
using HorseClub.BLL.Contracts;
using HorseClub.BLL.Messaging;
using HorseClub.DAL.Abstractions;
using Microsoft.Extensions.Options;
namespace HorseClub.BLL.Common;
public sealed class ManagementService(IManagementRepository repository,IUnitOfWork unitOfWork,CurrentUser current,ClubEvents events,PageReader pager,UploadStorage storage,AzureBlobStore blobs,IOptions<WebsiteOptions> options,IOptions<StorageOptions> limits,IOptions<BrandingOptions> branding,IOptions<BusinessOptions> business):IManagementService {
 private readonly WebsiteOptions settings=options.Value;
 private WebsiteContent Content(WebsiteSettings? row)=>row is null?settings.Defaults:JsonSerializer.Deserialize<WebsiteContent>(row.ContentJson)!;
 private WebsiteResponse View(WebsiteSettings? row){var c=Content(row);return new(row?.Version ?? -1,c.HeroTitle,c.HeroDescription,c.FeaturesTitle,c.FeaturesDescription,c.Features,row?.LogoName,row?.HeroName,row?.BackgroundName);}
 public async Task<WebsiteResponse> GetWebsite()=>View(await repository.GetWebsite());
 public static void ValidateContent(WebsiteContent c,WebsiteOptions options){
  bool Text(string? value,int max)=>!string.IsNullOrWhiteSpace(value)&&value.Length<=max&&!value.Any(c=>char.IsControl(c)&&c is not '\n' and not '\r' and not '\t');
  Ensure.That(Text(c.HeroTitle,options.TitleMaxLength)&&Text(c.FeaturesTitle,options.TitleMaxLength)&&Text(c.HeroDescription,options.DescriptionMaxLength)&&Text(c.FeaturesDescription,options.DescriptionMaxLength)&&c.Features is not null&&c.Features.Count==options.FeatureCount&&c.Features.All(f=>f is not null&&Text(f.Title,options.TitleMaxLength)&&Text(f.Description,options.DescriptionMaxLength)),Messages.Get(MessageKey.InvalidRequestBody));
 }
 private async Task<WebsiteSettings> Writable(long version){var row=await repository.GetWebsite();Ensure.That((row?.Version ?? -1)==version,Messages.Get(MessageKey.RecordChangedReloadAndRetry),409,"conflict");if(row is null){row=new(){Id=WebsiteSettings.PublicId,ContentJson=JsonSerializer.Serialize(settings.Defaults)};repository.AddWebsite(row);}return row;}
 public async Task<WebsiteResponse> UpdateWebsite(WebsiteRequest request){Ensure.Role(await current.Get(),Role.ClubManager);var content=new WebsiteContent(request.HeroTitle,request.HeroDescription,request.FeaturesTitle,request.FeaturesDescription,request.Features);ValidateContent(content,settings);var row=await Writable(request.Version);row.ContentJson=JsonSerializer.Serialize(content);await events.Audit(AuditAction.WebsiteContentUpdated,row.Id);await unitOfWork.SaveChangesAsync();return View(row);}
 public async Task<WebsiteResponse> UploadAsset(WebsiteAssetKind kind,UploadRequest request){
  Ensure.Role(await current.Get(),Role.ClubManager);Ensure.That(Enum.IsDefined(kind)&&request.HasFormContentType,Messages.Get(MessageKey.InvalidRequestBody));var form=await request.ReadFormAsync();Ensure.That(long.TryParse(form["version"],out var version),Messages.Get(MessageKey.InvalidRequestBody));var row=await Writable(version);var file=form.Files.GetFile("file");Ensure.That(form.Files.Items.Count==1&&file is not null&&file.Length>0&&file.Length<=limits.Value.MaxFileBytes,Messages.Get(MessageKey.InvalidRequestBody));var bytes=new byte[checked((int)file!.Length)];await using(var stream=file.OpenReadStream())await stream.ReadExactlyAsync(bytes,request.CancellationToken);var type=AttachmentService.Detect(bytes);var extension=Path.GetExtension(file.FileName).ToLowerInvariant();Ensure.That(type=="image/png"&&extension==".png" || type=="image/jpeg"&&extension is ".jpg" or ".jpeg",Messages.Get(MessageKey.OnlyValidPNGJPEGOrPDFFilesAreAccepted));var name=Guid.NewGuid().ToString("N");await storage.Write(name,bytes,request.CancellationToken,type!);
  switch(kind){case WebsiteAssetKind.Logo:row.LogoName=name;row.LogoType=type;break;case WebsiteAssetKind.Hero:row.HeroName=name;row.HeroType=type;break;case WebsiteAssetKind.Background:row.BackgroundName=name;row.BackgroundType=type;break;}
  await events.Audit(AuditAction.WebsiteAssetUpdated,row.Id,kind.ToString());await unitOfWork.SaveChangesAsync();return View(row);
 }
 public async Task<OperationResult> OpenAsset(WebsiteAssetKind kind){Ensure.That(Enum.IsDefined(kind),Messages.Get(MessageKey.InvalidRequestBody));var row=await repository.GetWebsite();var (name,type)=kind switch{WebsiteAssetKind.Logo=>(row?.LogoName,row?.LogoType),WebsiteAssetKind.Hero=>(row?.HeroName,row?.HeroType),_=>(row?.BackgroundName,row?.BackgroundType)};if(name is null&&kind==WebsiteAssetKind.Logo)return OperationResult.File(await blobs.OpenRead(branding.Value.LogoBlobName,default),"image/png","logo.png");Ensure.That(name is not null,Messages.Get(MessageKey.StoredAttachmentIsUnavailable),404,"not_found");return OperationResult.File(await storage.OpenRead(name!),type!,kind.ToString());}
 public async Task<PageResponse<AuditReadModel>> ListAudit(Guid? referenceId,string? search,DateOnly? from,DateOnly? to,int? page,int? pageSize){Ensure.Role(await current.Get(),Role.ClubManager);Ensure.That(search is null||search.Length<=100,Messages.Get(MessageKey.InvalidRequestBody));Ensure.That(!from.HasValue||!to.HasValue||from<=to,Messages.Get(MessageKey.InvalidRequestBody));var zone=TimeZoneInfo.FindSystemTimeZoneById(business.Value.TimeZoneId);DateTimeOffset At(DateOnly day){var date=day.ToDateTime(TimeOnly.MinValue);return new DateTimeOffset(date,zone.GetUtcOffset(date)).ToUniversalTime();}return await pager.Page(page,pageSize,(p,size)=>repository.Audit(referenceId,search?.Trim(),from.HasValue?At(from.Value):null,to.HasValue?At(to.Value.AddDays(1)):null,p,size));}
}
